# 1. Routing untuk Tebu (Laravel)
server {
    listen 80;
    server_name sugarcane.sblampung.com;

    location / {
        proxy_pass http://tebu-app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# 2. Routing untuk Dazytech (Next.js)
server {
    listen 80;
    server_name dazytech.web.id www.dazytech.web.id;

    location / {
        proxy_pass http://dazytech-app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# 3. Routing untuk Trans Anugerah Nusa (DIKOMENTARI DULU)
# server {
#     listen 80;
#     server_name trans-anugerah-nusa.dazytech.web.id;
#
#     location / {
#         proxy_pass http://trans-app:80;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }
# }