# --- 1. REDIRECT HTTP KE HTTPS ---
server {
    listen 80;
    server_name tebu-test.dazytech.web.id dazy-test.dazytech.web.id;
    return 301 https://$host$request_uri;
}

# --- 2. KONFIGURASI HTTPS: TEBU TEST ---
server {
    listen 443 ssl;
    server_name tebu-test.dazytech.web.id;

    ssl_certificate /etc/letsencrypt/live/tebu-test.dazytech.web.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tebu-test.dazytech.web.id/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://tebu-app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /app/ {
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://tebu-app:8080;
    }
}

# --- 3. KONFIGURASI HTTPS: DAZYTECH TEST ---
server {
    listen 443 ssl;
    server_name dazy-test.dazytech.web.id;

    ssl_certificate /etc/letsencrypt/live/dazy-test.dazytech.web.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dazy-test.dazytech.web.id/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://dazytech-app:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}